# NUMPY EXERCISE

1. Import the numpy package under the name as np 

In [1]:
import numpy as np


2. Print the numpy version and the configuration

In [39]:
print(np.__version__)
np.__config__.show()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/soham/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/soham/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/soham/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

3. Create a null vector of size 10

In [2]:
a = np.zeros((1,10))

In [4]:
print("A null vector of size 10:\n",a)

A null vector of size 10:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


4. How to find the memory size of any array

In [48]:
t = np.array([[1,2,3],
              [4,2,6]])
print("Memory size of an array is:",t.size*t.itemsize,'bytes')

Memory size of an array is: 24 bytes


5. How to get the documentation of the numpy add function from the command line?

In [42]:
 import numpy; numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

6. Create a null vector of size 10 but the fifth value which is 1

In [43]:
y = np.zeros(10)
y[4]=1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [9]:
c = np.arange(10,50)
print("A vector with values ranging from 10 to 49 is:\n",c)

A vector with values ranging from 10 to 49 is:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [44]:
w = np.arange(10,50)
w= w[::-1]
print (w)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
e = np.arange(0,9).reshape(3,3)
print("A 3X3 matrix with values ranging from 0 to 8 is:\n",e)

A 3X3 matrix with values ranging from 0 to 8 is:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [17]:
f = np.array([1,2,0,0,4,0])
sub = np.where(f!=0)
print("The indices of non-zero elements is:\n",sub)

The indices of non-zero elements is:
 (array([0, 1, 4], dtype=int64),)


11. Create a 3x3 identity matrix

In [21]:
g =np.eye(3,3)
print("A 3X3 identity matix is:\n",g)

A 3X3 identity matix is:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values

In [22]:
h = np.random.random((3,3,3))
print("A 3X3 array with random values is:\n",h)

A 3X3 array with random values is:
 [[[0.1669554  0.26077256 0.42310055]
  [0.74576541 0.67463573 0.29895308]
  [0.12967265 0.7706221  0.4814603 ]]

 [[0.18736806 0.74614126 0.26743951]
  [0.833483   0.57638297 0.85346438]
  [0.80360806 0.16811544 0.48920441]]

 [[0.47974345 0.44016141 0.44804148]
  [0.70624303 0.56152911 0.24262566]
  [0.60251226 0.61437245 0.93181585]]]


13. Create a 10x10 array with random values and find the minimum and maximum values

In [25]:
i = np.random.random((10,10))
print("A 10X10 array with random values is:\n",i)
print("The maximum value is:",i.max())
print("The minimum value is:",i.min())

A 10X10 array with random values is:
 [[0.800966   0.77922735 0.45832693 0.33338321 0.88047433 0.03952143
  0.38980808 0.68095938 0.76588741 0.14387972]
 [0.99569507 0.56659656 0.5460097  0.06522431 0.7822974  0.10923362
  0.8298068  0.64566502 0.78434338 0.43628539]
 [0.06720585 0.12170839 0.22799428 0.66936423 0.76402113 0.07078103
  0.12726838 0.58418602 0.40310059 0.18645785]
 [0.36203977 0.65718242 0.00124759 0.8799371  0.22224292 0.69626088
  0.54173477 0.38356807 0.76460967 0.73578818]
 [0.52847331 0.07467543 0.53092931 0.11296122 0.4725746  0.46129888
  0.49217608 0.27179827 0.22180706 0.64691693]
 [0.14879573 0.29304891 0.44004813 0.61719838 0.66505262 0.07220975
  0.87386842 0.63187166 0.02158256 0.57394129]
 [0.11797684 0.40543254 0.88743826 0.6584752  0.00515362 0.59961539
  0.2226757  0.93610629 0.39237156 0.13931721]
 [0.94462313 0.15966925 0.07235262 0.60017805 0.27225931 0.2503817
  0.03211618 0.9969848  0.63155907 0.01456323]
 [0.45735744 0.63829833 0.02406936 0.439434

14. Create a random vector of size 30 and find the mean value

In [27]:
j = np.random.random((1,30))
print("A random vector of size 30 is:\n",j)
print("The mean value is:",np.mean(j))

A random vector of size 30 is:
 [[0.89017463 0.89324192 0.61828572 0.54396669 0.60441148 0.8935993
  0.85112328 0.48324395 0.31306889 0.07423064 0.93629907 0.58758079
  0.85749012 0.38483897 0.45591832 0.61176374 0.0284332  0.38357274
  0.86827073 0.4861681  0.05306274 0.11549131 0.62889344 0.27200636
  0.07145785 0.26376611 0.88234746 0.32746265 0.64833637 0.72227976]]
The mean value is: 0.5250262110000052


15. Create a 2d array with 1 on the border and 0 inside

In [30]:
k =np.ones((5,5))
print("Original array is :\n",k)
print("1 on the border and 0 inside in the array\n")
k[1:-1,1:-1]=0
print(k)

Original array is :
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array?

In [34]:
l = np.ones((3,3))
print("Original array is:\n",l)
print("Array with a border around the original array is\n")
l=np.pad(l,pad_width=1,mode='constant',constant_values=0)
print(l)

Original array is:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array with a border around the original array is

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


17. What is the result of the following expression?

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [35]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagona

In [36]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [37]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [38]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)
